# Generated by Django 4.2.7 on 2023-12-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_processing', '0001_initial'),
    ]

    operations = [
    ]
