# Generated by Django 4.2.7 on 2023-12-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_processing', '0002_auto_20231206_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaction',
            name='name',
            field=models.CharField(db_index=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentaction',
            name='owner_class',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
